"""empty message

Revision ID: 517db2bad3da
Revises: 
Create Date: 2019-11-09 14:29:39.522598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517db2bad3da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('categoryid')
    )
    op.create_table('gender',
    sa.Column('genderid', sa.Integer(), nullable=False),
    sa.Column('gender_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('genderid')
    )
    op.create_table('product',
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('image2', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('regular_price', sa.DECIMAL(), nullable=True),
    sa.Column('discounted_price', sa.DECIMAL(), nullable=True),
    sa.Column('product_rating', sa.DECIMAL(), nullable=True),
    sa.Column('product_review', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('productid')
    )
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=False),
    sa.Column('lname', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=8), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('usertype', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('order',
    sa.Column('orderid', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('total_price', sa.DECIMAL(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('orderid', 'userid')
    )
    op.create_table('product_category',
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoryid'], ['category.categoryid'], ),
    sa.ForeignKeyConstraint(['productid'], ['product.productid'], ),
    sa.PrimaryKeyConstraint('categoryid', 'productid')
    )
    op.create_table('product_gender',
    sa.Column('genderid', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['genderid'], ['gender.genderid'], ),
    sa.ForeignKeyConstraint(['productid'], ['product.productid'], ),
    sa.PrimaryKeyConstraint('genderid', 'productid')
    )
    op.create_table('size',
    sa.Column('sizeid', sa.Integer(), nullable=False),
    sa.Column('size_name', sa.String(length=20), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['productid'], ['product.productid'], ),
    sa.PrimaryKeyConstraint('sizeid')
    )
    op.create_table('cart',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('sizeid', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productid'], ['product.productid'], ),
    sa.ForeignKeyConstraint(['sizeid'], ['size.sizeid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('userid', 'productid')
    )
    op.create_table('ordered_product',
    sa.Column('ordproductid', sa.Integer(), nullable=False),
    sa.Column('orderid', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=True),
    sa.Column('sizeid', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orderid'], ['order.orderid'], ),
    sa.ForeignKeyConstraint(['productid'], ['product.productid'], ),
    sa.ForeignKeyConstraint(['sizeid'], ['size.sizeid'], ),
    sa.PrimaryKeyConstraint('ordproductid')
    )
    op.create_table('sale_transaction',
    sa.Column('transactionid', sa.Integer(), nullable=False),
    sa.Column('orderid', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('cc_number', sa.String(length=50), nullable=False),
    sa.Column('cc_type', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('response', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['orderid'], ['order.orderid'], ),
    sa.PrimaryKeyConstraint('transactionid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_transaction')
    op.drop_table('ordered_product')
    op.drop_table('cart')
    op.drop_table('size')
    op.drop_table('product_gender')
    op.drop_table('product_category')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('gender')
    op.drop_table('category')
    # ### end Alembic commands ###
