"""empty message

Revision ID: c7e1328c40a8
Revises: 8782bb251034
Create Date: 2019-11-03 22:41:52.510559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e1328c40a8'
down_revision = '8782bb251034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ordered_product', 'order', ['orderid'], ['orderid'])
    op.create_foreign_key(None, 'sale_transaction', 'order', ['orderid'], ['orderid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_transaction', type_='foreignkey')
    op.drop_constraint(None, 'ordered_product', type_='foreignkey')
    # ### end Alembic commands ###
